---
language: ruby
rvm:
- 1.9.3
script: bundle exec rake test
notifications:
  recipients:
    - jonah@pixelhipsters.com
  irc:
    on_success: change
    on_failure: always
    channels:
    - irc.freenode.org#rubyonadhd